"""Offline integrity checks for the pinned AgentDojo execution environment.

The published wheel digest and an installed distribution are different byte
representations.  This module never claims that hashing an unpacked
``site-packages`` tree reproduces a wheel SHA.  Instead it supports two honest
verification modes:

* when an operator supplies the published wheel, its archive SHA is checked
  and its immutable payload is compared byte-for-byte with the installation;
* otherwise the installed immutable payload is checked against a canonical
  payload fingerprint frozen from that published wheel.

All checks are local and perform no package resolution or network access.
"""

from __future__ import annotations

import argparse
from dataclasses import asdict, dataclass
from email.parser import BytesParser
import hashlib
from importlib import metadata
import json
from pathlib import Path, PurePosixPath
import platform
import re
import sys
import sysconfig
from typing import Any, Callable, Iterable, Mapping, Sequence
import zipfile

from .config import AGENTDOJO_PACKAGE_VERSION


EXPECTED_WHEEL_SHA256 = "364bea4219716b716bf639f504d195943f7f6a5535d312ca41d7098704a2affd"
EXPECTED_SDIST_SHA256 = "9eacbc89d996f8656b235ad7b626bcf840b1ace7101174ca62d790c7c6d62956"
# SHA-256 of the canonical JSON manifest (path, byte SHA-256, byte count) of
# the 115 immutable payload files in the published wheel above.  RECORD itself
# is excluded because installation legitimately rewrites it; INSTALLER,
# REQUESTED, direct_url.json, and generated bytecode are installation state.
EXPECTED_INSTALLED_PAYLOAD_SHA256 = (
    "bce8c4f279da44fe88e7e69625d0e37a93ba60fda3a057b11b239be2b3b10b77"
)
EXPECTED_INSTALLED_PAYLOAD_FILE_COUNT = 115
EXPECTED_CORE_DISTRIBUTION_COUNT = 71
EXPECTED_PYTHON = (3, 11)
RUNTIME_FINGERPRINT_SCHEMA = "silenttwin.agentdojo.learned-runtime/v1"
RUNTIME_PROVENANCE_SCHEMA = (
    "silenttwin.agentdojo.learned-runtime-provenance/v1"
)
INSTALLED_WHEEL_VERIFICATION_SCHEMA = (
    "silenttwin.agentdojo.installed-wheel-verification/v1"
)
_EXACT_REQUIREMENT = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)==([^\s;]+)$")
_LEARNED_RUNTIME_MINIMUM = frozenset({"torch", "transformers"})
_HEX_SHA256 = re.compile(r"^[0-9a-f]{64}$")


class RuntimeIntegrityError(RuntimeError):
    """The local package/runtime bytes differ from a frozen identity."""


@dataclass(frozen=True, slots=True)
class DistributionIntegrityReport:
    package_version: str
    verification_mode: str
    installed_payload_sha256: str
    installed_payload_file_count: int
    expected_wheel_sha256: str
    wheel_artifact_sha256: str | None

    @property
    def wheel_artifact_verified(self) -> bool:
        return self.wheel_artifact_sha256 == self.expected_wheel_sha256

    def to_dict(self) -> dict[str, Any]:
        return {**asdict(self), "wheel_artifact_verified": self.wheel_artifact_verified}


@dataclass(frozen=True, slots=True)
class LockedEnvironmentReport:
    lock_sha256: str
    distribution_count: int
    requirements: tuple[tuple[str, str], ...]

    def to_dict(self) -> dict[str, Any]:
        return {
            "lock_sha256": self.lock_sha256,
            "distribution_count": self.distribution_count,
            "requirements": [
                {"name": name, "version": version}
                for name, version in self.requirements
            ],
        }


@dataclass(frozen=True, slots=True)
class LearnedRuntimeReport:
    fingerprint: str
    distribution_count: int
    manifest: Mapping[str, Any]

    def to_dict(self, *, include_manifest: bool = False) -> dict[str, Any]:
        value: dict[str, Any] = {
            "runtime_fingerprint": self.fingerprint,
            "distribution_count": self.distribution_count,
        }
        if include_manifest:
            value["manifest"] = self.manifest
        return value


@dataclass(frozen=True, slots=True)
class RuntimeIntegrityReport:
    agentdojo: DistributionIntegrityReport
    locked_environment: LockedEnvironmentReport
    learned_runtime: LearnedRuntimeReport

    def to_dict(self, *, include_manifest: bool = False) -> dict[str, Any]:
        return {
            "agentdojo_distribution": self.agentdojo.to_dict(),
            "locked_environment": self.locked_environment.to_dict(),
            "learned_runtime": self.learned_runtime.to_dict(
                include_manifest=include_manifest
            ),
        }


def not_applicable_learned_runtime_provenance() -> dict[str, Any]:
    """Return the canonical sentinel retained by model-free executions."""

    return {
        "schema_version": RUNTIME_PROVENANCE_SCHEMA,
        "status": "not_applicable",
        "runtime_fingerprint": "not_applicable",
        "manifest": "not_applicable",
    }


def _canonical_json_sha256(value: Any) -> str:
    encoded = json.dumps(
        value,
        ensure_ascii=True,
        sort_keys=True,
        separators=(",", ":"),
        allow_nan=False,
    ).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def _file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _normalize_name(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def _is_immutable_payload_path(raw_path: str) -> bool:
    path = PurePosixPath(raw_path)
    if path.is_absolute() or ".." in path.parts or not path.parts:
        raise RuntimeIntegrityError(f"unsafe distribution payload path {raw_path!r}")
    normalized = path.as_posix()
    if "__pycache__" in path.parts or normalized.endswith(".pyc"):
        return False
    basename = path.name
    if basename in {"RECORD", "INSTALLER", "REQUESTED", "direct_url.json"}:
        return False
    first = path.parts[0]
    return first == "agentdojo" or first == (
        f"agentdojo-{AGENTDOJO_PACKAGE_VERSION}.dist-info"
    )


def _manifest_entry(path: str, content: bytes) -> dict[str, Any]:
    return {
        "path": path,
        "sha256": hashlib.sha256(content).hexdigest(),
        "size": len(content),
    }


def _installed_payload_manifest(distribution: Any) -> list[dict[str, Any]]:
    files = distribution.files
    if files is None:
        raise RuntimeIntegrityError("agentdojo installation exposes no RECORD file list")
    result: list[dict[str, Any]] = []
    observed: set[str] = set()
    for item in files:
        relative = PurePosixPath(str(item)).as_posix()
        if not _is_immutable_payload_path(relative):
            continue
        if relative in observed:
            raise RuntimeIntegrityError(f"duplicate installed payload path {relative!r}")
        observed.add(relative)
        resolved = Path(distribution.locate_file(item))
        if resolved.is_symlink() or not resolved.is_file():
            raise RuntimeIntegrityError(
                f"installed AgentDojo payload is missing or non-regular: {relative}"
            )
        try:
            content = resolved.read_bytes()
        except OSError as error:
            raise RuntimeIntegrityError(
                f"cannot read installed AgentDojo payload {relative}: {error}"
            ) from error
        result.append(_manifest_entry(relative, content))
    return sorted(result, key=lambda row: str(row["path"]))


def _wheel_payload_manifest(path: Path) -> list[dict[str, Any]]:
    result: list[dict[str, Any]] = []
    observed: set[str] = set()
    try:
        with zipfile.ZipFile(path) as archive:
            for member in archive.infolist():
                relative = PurePosixPath(member.filename).as_posix()
                if member.is_dir() or not _is_immutable_payload_path(relative):
                    continue
                if relative in observed:
                    raise RuntimeIntegrityError(
                        f"duplicate wheel payload path {relative!r}"
                    )
                observed.add(relative)
                result.append(_manifest_entry(relative, archive.read(member)))
    except (OSError, zipfile.BadZipFile, KeyError) as error:
        raise RuntimeIntegrityError(f"cannot inspect AgentDojo wheel {path}: {error}") from error
    return sorted(result, key=lambda row: str(row["path"]))


def verify_agentdojo_distribution(
    *,
    wheel_artifact: Path | str | None = None,
    distribution: Any | None = None,
    expected_wheel_sha256: str = EXPECTED_WHEEL_SHA256,
    expected_payload_sha256: str = EXPECTED_INSTALLED_PAYLOAD_SHA256,
    expected_payload_file_count: int = EXPECTED_INSTALLED_PAYLOAD_FILE_COUNT,
) -> DistributionIntegrityReport:
    """Verify AgentDojo's installed bytes, and an exact wheel when supplied."""

    try:
        installed = distribution or metadata.distribution("agentdojo")
    except metadata.PackageNotFoundError as error:
        raise RuntimeIntegrityError("agentdojo is not installed") from error
    version = str(installed.version)
    if version != AGENTDOJO_PACKAGE_VERSION:
        raise RuntimeIntegrityError(
            f"agentdojo=={AGENTDOJO_PACKAGE_VERSION} required, found {version}"
        )
    installed_manifest = _installed_payload_manifest(installed)
    installed_fingerprint = _canonical_json_sha256(installed_manifest)
    if len(installed_manifest) != expected_payload_file_count:
        raise RuntimeIntegrityError(
            "installed AgentDojo immutable payload file count drifted: "
            f"expected {expected_payload_file_count}, found {len(installed_manifest)}"
        )
    if installed_fingerprint != expected_payload_sha256:
        raise RuntimeIntegrityError(
            "installed AgentDojo immutable payload bytes differ from the frozen "
            "published-wheel payload manifest"
        )

    wheel_digest: str | None = None
    verification_mode = "installed_payload_against_frozen_wheel_payload_manifest"
    if wheel_artifact is not None:
        wheel_path = Path(wheel_artifact).expanduser()
        if wheel_path.is_symlink() or not wheel_path.is_file():
            raise RuntimeIntegrityError(
                "operator-supplied AgentDojo wheel must be a local regular file"
            )
        wheel_digest = _file_sha256(wheel_path)
        if wheel_digest != expected_wheel_sha256:
            raise RuntimeIntegrityError(
                "operator-supplied AgentDojo wheel SHA-256 does not match the "
                "published frozen digest"
            )
        wheel_manifest = _wheel_payload_manifest(wheel_path)
        if wheel_manifest != installed_manifest:
            raise RuntimeIntegrityError(
                "installed AgentDojo payload differs from the verified wheel artifact"
            )
        verification_mode = "verified_published_wheel_and_matching_installed_payload"

    return DistributionIntegrityReport(
        package_version=version,
        verification_mode=verification_mode,
        installed_payload_sha256=installed_fingerprint,
        installed_payload_file_count=len(installed_manifest),
        expected_wheel_sha256=expected_wheel_sha256,
        wheel_artifact_sha256=wheel_digest,
    )


def parse_exact_lock(
    dependency_lock_path: Path | str,
    *,
    expected_count: int | None = EXPECTED_CORE_DISTRIBUTION_COUNT,
) -> tuple[tuple[str, str], ...]:
    """Parse a no-options, exact-version lock without invoking a resolver."""

    path = Path(dependency_lock_path)
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except OSError as error:
        raise RuntimeIntegrityError(f"cannot read dependency lock {path}: {error}") from error
    requirements: dict[str, str] = {}
    for line_number, raw_line in enumerate(lines, 1):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        match = _EXACT_REQUIREMENT.fullmatch(line)
        if match is None:
            raise RuntimeIntegrityError(
                f"dependency lock line {line_number} is not one exact name==version pin"
            )
        name = _normalize_name(match.group(1))
        version = match.group(2)
        if name in requirements:
            raise RuntimeIntegrityError(f"dependency lock repeats distribution {name!r}")
        requirements[name] = version
    if expected_count is not None and len(requirements) != expected_count:
        raise RuntimeIntegrityError(
            f"dependency lock must contain {expected_count} distributions, "
            f"found {len(requirements)}"
        )
    if requirements.get("agentdojo") != AGENTDOJO_PACKAGE_VERSION:
        raise RuntimeIntegrityError(
            f"dependency lock must pin agentdojo=={AGENTDOJO_PACKAGE_VERSION}"
        )
    return tuple(sorted(requirements.items()))


def validate_locked_distributions(
    dependency_lock_path: Path | str,
    *,
    version_resolver: Callable[[str], str] = metadata.version,
    expected_count: int | None = EXPECTED_CORE_DISTRIBUTION_COUNT,
) -> LockedEnvironmentReport:
    """Compare every exact core lock pin with the active environment."""

    path = Path(dependency_lock_path)
    requirements = parse_exact_lock(path, expected_count=expected_count)
    mismatches: list[str] = []
    for name, expected in requirements:
        try:
            observed = version_resolver(name)
        except metadata.PackageNotFoundError:
            mismatches.append(f"{name}:missing (expected {expected})")
            continue
        if observed != expected:
            mismatches.append(f"{name}:{observed} (expected {expected})")
    if mismatches:
        preview = ", ".join(mismatches[:8])
        if len(mismatches) > 8:
            preview += f", ... ({len(mismatches)} total)"
        raise RuntimeIntegrityError(f"installed core lock drift: {preview}")
    return LockedEnvironmentReport(
        lock_sha256=_file_sha256(path),
        distribution_count=len(requirements),
        requirements=requirements,
    )


def _record_identity(distribution: Any) -> str:
    """Hash immutable RECORD identities without reading multi-GB model stacks."""

    files = distribution.files
    if files is None:
        return "record-unavailable"
    rows: list[dict[str, Any]] = []
    for item in files:
        path = PurePosixPath(str(item))
        if (
            "__pycache__" in path.parts
            or path.suffix == ".pyc"
            or path.name in {"RECORD", "INSTALLER", "REQUESTED", "direct_url.json"}
        ):
            continue
        file_hash = getattr(item, "hash", None)
        hash_value = None
        if file_hash is not None:
            hash_value = f"{file_hash.mode}:{file_hash.value}"
        rows.append(
            {
                "path": path.as_posix(),
                "record_hash": hash_value,
                "record_size": getattr(item, "size", None),
            }
        )
    rows.sort(key=lambda row: str(row["path"]))
    return _canonical_json_sha256(rows)


def verify_installed_distribution_against_wheel(
    *,
    wheel_artifact: Path | str,
    distribution_name: str,
    expected_version: str,
    distribution: Any | None = None,
) -> dict[str, Any]:
    """Compare every immutable wheel payload byte with one installation.

    RECORD and installer-generated state are excluded because installers
    legitimately rewrite or add them.  The wheel archive hash, installed
    RECORD identity, and a canonical path/byte manifest remain separate
    identities in the returned self-hashed report.
    """

    wheel_path = Path(wheel_artifact).expanduser()
    if wheel_path.is_symlink() or not wheel_path.is_file():
        raise RuntimeIntegrityError("wheel artifact must be a local regular file")
    installed = (
        distribution
        if distribution is not None
        else metadata.distribution(distribution_name)
    )
    observed_name = installed.metadata.get("Name")
    if (
        not isinstance(observed_name, str)
        or _normalize_name(observed_name) != _normalize_name(distribution_name)
        or str(installed.version) != expected_version
    ):
        raise RuntimeIntegrityError(
            "installed distribution name/version differs from the wheel contract"
        )
    rows: list[dict[str, Any]] = []
    observed: set[str] = set()
    excluded_names = {"RECORD", "INSTALLER", "REQUESTED", "direct_url.json"}
    try:
        with zipfile.ZipFile(wheel_path) as archive:
            members = archive.infolist()
            metadata_members = [
                member
                for member in members
                if not member.is_dir()
                and PurePosixPath(member.filename).name == "METADATA"
                and PurePosixPath(member.filename).parent.name.endswith(
                    ".dist-info"
                )
            ]
            if len(metadata_members) != 1:
                raise RuntimeIntegrityError(
                    "wheel must contain exactly one distribution METADATA file"
                )
            metadata_member = metadata_members[0]
            wheel_metadata = BytesParser().parsebytes(
                archive.read(metadata_member)
            )
            if (
                _normalize_name(str(wheel_metadata.get("Name", "")))
                != _normalize_name(distribution_name)
                or str(wheel_metadata.get("Version", "")) != expected_version
            ):
                raise RuntimeIntegrityError(
                    "wheel metadata differs from the distribution contract"
                )
            dist_info = PurePosixPath(metadata_member.filename).parent
            record_name = (dist_info / "RECORD").as_posix()
            if sum(member.filename == record_name for member in members) != 1:
                raise RuntimeIntegrityError(
                    "wheel must contain exactly one matching RECORD file"
                )
            for member in members:
                path = PurePosixPath(member.filename)
                relative = path.as_posix()
                if member.is_dir() or path.name in excluded_names:
                    continue
                if path.is_absolute() or ".." in path.parts or not path.parts:
                    raise RuntimeIntegrityError(
                        f"unsafe wheel payload path {relative!r}"
                    )
                if relative in observed:
                    raise RuntimeIntegrityError(
                        f"duplicate wheel payload path {relative!r}"
                    )
                observed.add(relative)
                wheel_bytes = archive.read(member)
                installed_path = Path(installed.locate_file(relative))
                if installed_path.is_symlink() or not installed_path.is_file():
                    raise RuntimeIntegrityError(
                        f"installed wheel payload is missing or non-regular: {relative}"
                    )
                installed_bytes = installed_path.read_bytes()
                if installed_bytes != wheel_bytes:
                    raise RuntimeIntegrityError(
                        f"installed payload differs from wheel at {relative}"
                    )
                rows.append(_manifest_entry(relative, wheel_bytes))
    except (OSError, zipfile.BadZipFile, KeyError) as exc:
        raise RuntimeIntegrityError(f"cannot verify installed wheel: {exc}") from exc
    rows.sort(key=lambda row: str(row["path"]))
    if not rows:
        raise RuntimeIntegrityError("wheel contains no immutable payload files")
    payload = {
        "schema_version": INSTALLED_WHEEL_VERIFICATION_SCHEMA,
        "distribution_name": _normalize_name(distribution_name),
        "distribution_version": expected_version,
        "wheel_filename": wheel_path.name,
        "wheel_sha256": _file_sha256(wheel_path),
        "immutable_payload_file_count": len(rows),
        "immutable_payload_manifest_sha256": _canonical_json_sha256(rows),
        "installed_record_identity": _record_identity(installed),
        "installed_payload_matches_wheel": True,
    }
    report = {**payload, "verification_hash": _canonical_json_sha256(payload)}
    validate_installed_wheel_verification(
        report,
        expected_distribution_name=distribution_name,
        expected_version=expected_version,
    )
    return report


def validate_installed_wheel_verification(
    report: Mapping[str, Any],
    *,
    expected_distribution_name: str,
    expected_version: str,
) -> str:
    """Validate the exact self-hashed installed-wheel verification envelope."""

    expected_fields = {
        "schema_version",
        "distribution_name",
        "distribution_version",
        "wheel_filename",
        "wheel_sha256",
        "immutable_payload_file_count",
        "immutable_payload_manifest_sha256",
        "installed_record_identity",
        "installed_payload_matches_wheel",
        "verification_hash",
    }
    if set(report) != expected_fields:
        raise RuntimeIntegrityError(
            "installed-wheel verification fields are not exact"
        )
    if report.get("schema_version") != INSTALLED_WHEEL_VERIFICATION_SCHEMA:
        raise RuntimeIntegrityError(
            "unsupported installed-wheel verification schema"
        )
    normalized_name = _normalize_name(expected_distribution_name)
    count = report.get("immutable_payload_file_count")
    filename = report.get("wheel_filename")
    if (
        report.get("distribution_name") != normalized_name
        or report.get("distribution_version") != expected_version
        or not isinstance(filename, str)
        or not filename.endswith(".whl")
        or Path(filename).name != filename
        or isinstance(count, bool)
        or not isinstance(count, int)
        or count <= 0
        or report.get("installed_payload_matches_wheel") is not True
    ):
        raise RuntimeIntegrityError(
            "installed-wheel verification does not satisfy its distribution contract"
        )
    for field in (
        "wheel_sha256",
        "immutable_payload_manifest_sha256",
        "installed_record_identity",
        "verification_hash",
    ):
        value = report.get(field)
        if not isinstance(value, str) or _HEX_SHA256.fullmatch(value) is None:
            raise RuntimeIntegrityError(
                f"installed-wheel verification has invalid {field}"
            )
    recorded = str(report["verification_hash"])
    payload = dict(report)
    payload.pop("verification_hash")
    if recorded != _canonical_json_sha256(payload):
        raise RuntimeIntegrityError(
            "installed-wheel verification hash does not match its payload"
        )
    return recorded


def _default_python_identity() -> dict[str, Any]:
    return {
        "implementation": sys.implementation.name,
        "version": list(sys.version_info[:3]),
        "cache_tag": sys.implementation.cache_tag,
        "abi_flags": getattr(sys, "abiflags", ""),
        "soabi": sysconfig.get_config_var("SOABI"),
        "byteorder": sys.byteorder,
        "system": platform.system(),
        "machine": platform.machine(),
    }


def derive_learned_runtime_fingerprint(
    dependency_lock_path: Path | str,
    *,
    distributions: Iterable[Any] | None = None,
    version_resolver: Callable[[str], str] = metadata.version,
    expected_lock_count: int | None = EXPECTED_CORE_DISTRIBUTION_COUNT,
    require_learned_stack: bool = True,
    python_identity: Mapping[str, Any] | None = None,
) -> LearnedRuntimeReport:
    """Derive a path-independent identity from the active package environment."""

    locked = validate_locked_distributions(
        dependency_lock_path,
        version_resolver=version_resolver,
        expected_count=expected_lock_count,
    )
    installed = tuple(metadata.distributions() if distributions is None else distributions)
    rows: dict[str, dict[str, Any]] = {}
    for distribution in installed:
        raw_name = distribution.metadata.get("Name")
        if not raw_name:
            raise RuntimeIntegrityError("installed distribution has no Name metadata")
        name = _normalize_name(str(raw_name))
        if name in rows:
            raise RuntimeIntegrityError(
                f"active environment contains duplicate distribution {name!r}"
            )
        rows[name] = {
            "name": name,
            "version": str(distribution.version),
            "record_identity": _record_identity(distribution),
        }
    if require_learned_stack:
        missing = sorted(_LEARNED_RUNTIME_MINIMUM - set(rows))
        if missing:
            raise RuntimeIntegrityError(
                "learned runtime lacks required distributions: " + ", ".join(missing)
            )
    manifest = {
        "schema_version": RUNTIME_FINGERPRINT_SCHEMA,
        "python": dict(python_identity or _default_python_identity()),
        "locked_core": [
            {"name": name, "version": version}
            for name, version in sorted(locked.requirements)
        ],
        "installed_distributions": [rows[name] for name in sorted(rows)],
    }
    fingerprint = f"sha256:{_canonical_json_sha256(manifest)}"
    return LearnedRuntimeReport(
        fingerprint=fingerprint,
        distribution_count=len(rows),
        manifest=manifest,
    )


def learned_runtime_manifest_fingerprint(manifest: Mapping[str, Any]) -> str:
    """Validate and hash one complete learned-runtime manifest.

    The returned value is the exact identity frozen into learned model rows.
    Validation is intentionally path-independent: distribution RECORD entries
    are represented by their immutable identity digest rather than by local
    installation paths.
    """

    if set(manifest) != {
        "schema_version",
        "python",
        "locked_core",
        "installed_distributions",
    }:
        raise RuntimeIntegrityError("learned-runtime manifest has invalid fields")
    if manifest.get("schema_version") != RUNTIME_FINGERPRINT_SCHEMA:
        raise RuntimeIntegrityError("unsupported learned-runtime manifest schema")

    python_identity = manifest.get("python")
    if not isinstance(python_identity, Mapping) or set(python_identity) != {
        "implementation",
        "version",
        "cache_tag",
        "abi_flags",
        "soabi",
        "byteorder",
        "system",
        "machine",
    }:
        raise RuntimeIntegrityError("learned-runtime manifest has incomplete Python identity")
    version = python_identity.get("version")
    if (
        not isinstance(version, list)
        or len(version) != 3
        or any(isinstance(item, bool) or not isinstance(item, int) for item in version)
    ):
        raise RuntimeIntegrityError("learned-runtime Python version must have three integers")
    for field in ("implementation", "cache_tag", "byteorder", "system", "machine"):
        if not isinstance(python_identity.get(field), str) or not python_identity[field]:
            raise RuntimeIntegrityError(
                f"learned-runtime Python identity has invalid {field}"
            )
    if not isinstance(python_identity.get("abi_flags"), str) or not (
        python_identity.get("soabi") is None
        or isinstance(python_identity.get("soabi"), str)
    ):
        raise RuntimeIntegrityError("learned-runtime Python ABI identity is invalid")

    locked_core = manifest.get("locked_core")
    if not isinstance(locked_core, list) or not locked_core:
        raise RuntimeIntegrityError("learned-runtime manifest lacks its locked core")
    locked_names: list[str] = []
    for index, row in enumerate(locked_core):
        if not isinstance(row, Mapping) or set(row) != {"name", "version"}:
            raise RuntimeIntegrityError(
                f"learned-runtime locked-core row {index} is invalid"
            )
        name = row.get("name")
        locked_version = row.get("version")
        if (
            not isinstance(name, str)
            or not name
            or name != _normalize_name(name)
            or not isinstance(locked_version, str)
            or not locked_version
        ):
            raise RuntimeIntegrityError(
                f"learned-runtime locked-core row {index} has invalid identity"
            )
        locked_names.append(name)
    if locked_names != sorted(set(locked_names)):
        raise RuntimeIntegrityError(
            "learned-runtime locked-core rows must be unique and sorted"
        )

    installed = manifest.get("installed_distributions")
    if not isinstance(installed, list) or not installed:
        raise RuntimeIntegrityError(
            "learned-runtime manifest lacks installed distributions"
        )
    installed_names: list[str] = []
    for index, row in enumerate(installed):
        if not isinstance(row, Mapping) or set(row) != {
            "name",
            "version",
            "record_identity",
        }:
            raise RuntimeIntegrityError(
                f"learned-runtime distribution row {index} is invalid"
            )
        name = row.get("name")
        installed_version = row.get("version")
        record_identity = row.get("record_identity")
        if (
            not isinstance(name, str)
            or not name
            or name != _normalize_name(name)
            or not isinstance(installed_version, str)
            or not installed_version
            or not isinstance(record_identity, str)
            or (
                record_identity != "record-unavailable"
                and _HEX_SHA256.fullmatch(record_identity) is None
            )
        ):
            raise RuntimeIntegrityError(
                f"learned-runtime distribution row {index} has invalid identity"
            )
        installed_names.append(name)
    if installed_names != sorted(set(installed_names)):
        raise RuntimeIntegrityError(
            "learned-runtime distribution rows must be unique and sorted"
        )
    missing = sorted(_LEARNED_RUNTIME_MINIMUM - set(installed_names))
    if missing:
        raise RuntimeIntegrityError(
            "learned-runtime manifest lacks required distributions: "
            + ", ".join(missing)
        )
    return f"sha256:{_canonical_json_sha256(manifest)}"


def make_learned_runtime_provenance(
    report: LearnedRuntimeReport,
) -> dict[str, Any]:
    """Build the retained, self-verifying provenance envelope for a report."""

    manifest = dict(report.manifest)
    fingerprint = learned_runtime_manifest_fingerprint(manifest)
    if report.fingerprint != fingerprint:
        raise RuntimeIntegrityError(
            "learned-runtime report fingerprint does not match its manifest"
        )
    installed = manifest["installed_distributions"]
    if report.distribution_count != len(installed):
        raise RuntimeIntegrityError(
            "learned-runtime report distribution count does not match its manifest"
        )
    return {
        "schema_version": RUNTIME_PROVENANCE_SCHEMA,
        "status": "captured",
        "runtime_fingerprint": fingerprint,
        "distribution_count": report.distribution_count,
        "manifest": manifest,
    }


def validate_learned_runtime_provenance(
    provenance: Mapping[str, Any],
    *,
    expected_runtime_fingerprints: Iterable[str] | None = None,
) -> str:
    """Validate retained runtime provenance and its optional frozen bindings."""

    expected = (
        None
        if expected_runtime_fingerprints is None
        else {str(item) for item in expected_runtime_fingerprints}
    )
    if expected is not None and len(expected) > 1:
        raise RuntimeIntegrityError(
            "one execution cannot bind multiple learned-runtime fingerprints"
        )
    status = provenance.get("status")
    if status == "not_applicable":
        if dict(provenance) != not_applicable_learned_runtime_provenance():
            raise RuntimeIntegrityError(
                "model-free learned-runtime provenance sentinel is not canonical"
            )
        if expected:
            raise RuntimeIntegrityError(
                "learned model identities cannot use not_applicable runtime provenance"
            )
        return "not_applicable"
    if set(provenance) != {
        "schema_version",
        "status",
        "runtime_fingerprint",
        "distribution_count",
        "manifest",
    } or provenance.get("schema_version") != RUNTIME_PROVENANCE_SCHEMA:
        raise RuntimeIntegrityError("learned-runtime provenance envelope is invalid")
    if status != "captured":
        raise RuntimeIntegrityError("learned-runtime provenance has invalid status")
    manifest = provenance.get("manifest")
    if not isinstance(manifest, Mapping):
        raise RuntimeIntegrityError("learned-runtime provenance lacks its manifest")
    fingerprint = learned_runtime_manifest_fingerprint(manifest)
    if provenance.get("runtime_fingerprint") != fingerprint:
        raise RuntimeIntegrityError(
            "learned-runtime provenance fingerprint does not match its manifest"
        )
    distribution_count = provenance.get("distribution_count")
    if (
        isinstance(distribution_count, bool)
        or not isinstance(distribution_count, int)
        or distribution_count != len(manifest["installed_distributions"])
    ):
        raise RuntimeIntegrityError(
            "learned-runtime provenance distribution count is invalid"
        )
    if expected is not None and expected != {fingerprint}:
        raise RuntimeIntegrityError(
            "learned-runtime provenance does not match frozen model identities"
        )
    return fingerprint


def capture_learned_runtime_provenance(
    dependency_lock_path: Path | str,
    *,
    expected_runtime_fingerprints: Iterable[str],
) -> dict[str, Any]:
    """Capture the active learned stack or the canonical model-free sentinel."""

    expected = {str(item) for item in expected_runtime_fingerprints}
    if not expected:
        return not_applicable_learned_runtime_provenance()
    report = derive_learned_runtime_fingerprint(
        dependency_lock_path, require_learned_stack=True
    )
    provenance = make_learned_runtime_provenance(report)
    validate_learned_runtime_provenance(
        provenance, expected_runtime_fingerprints=expected
    )
    return provenance


def verify_runtime_environment(
    dependency_lock_path: Path | str,
    *,
    wheel_artifact: Path | str | None = None,
    require_learned_stack: bool = True,
) -> RuntimeIntegrityReport:
    """Run the complete offline package and learned-runtime preflight."""

    if sys.version_info[:2] != EXPECTED_PYTHON:
        raise RuntimeIntegrityError(
            "AgentDojo Tier-2 requires Python 3.11 exactly; "
            f"running {sys.version_info.major}.{sys.version_info.minor}"
        )
    agentdojo = verify_agentdojo_distribution(wheel_artifact=wheel_artifact)
    locked = validate_locked_distributions(dependency_lock_path)
    learned = derive_learned_runtime_fingerprint(
        dependency_lock_path,
        require_learned_stack=require_learned_stack,
    )
    return RuntimeIntegrityReport(
        agentdojo=agentdojo,
        locked_environment=locked,
        learned_runtime=learned,
    )


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="python -m silenttwin.agentdojo.runtime_integrity",
        description="Offline AgentDojo package/runtime integrity preflight.",
    )
    parser.add_argument(
        "--dependency-lock",
        type=Path,
        default=Path("requirements-tier2-agentdojo.lock"),
        help="exact 71-distribution core lock (default: %(default)s)",
    )
    parser.add_argument(
        "--wheel-artifact",
        type=Path,
        help="optional local agentdojo-0.1.35 wheel to verify against its published SHA",
    )
    parser.add_argument(
        "--include-manifest",
        action="store_true",
        help="include the canonical runtime manifest used for the fingerprint",
    )
    parser.add_argument(
        "--fingerprint-only",
        action="store_true",
        help="print only the exact sha256:... value for a frozen grid/profile",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    parser = _parser()
    args = parser.parse_args(argv)
    try:
        report = verify_runtime_environment(
            args.dependency_lock,
            wheel_artifact=args.wheel_artifact,
            require_learned_stack=True,
        )
    except Exception as error:
        parser.exit(2, f"AgentDojo runtime integrity error: {type(error).__name__}: {error}\n")
    if args.fingerprint_only:
        print(report.learned_runtime.fingerprint)
        return 0
    print(
        json.dumps(
            report.to_dict(include_manifest=args.include_manifest),
            ensure_ascii=True,
            sort_keys=True,
            separators=(",", ":"),
            allow_nan=False,
        )
    )
    return 0


if __name__ == "__main__":  # pragma: no cover - exercised as a module command
    raise SystemExit(main())


__all__ = [
    "DistributionIntegrityReport",
    "EXPECTED_CORE_DISTRIBUTION_COUNT",
    "EXPECTED_INSTALLED_PAYLOAD_FILE_COUNT",
    "EXPECTED_INSTALLED_PAYLOAD_SHA256",
    "EXPECTED_PYTHON",
    "EXPECTED_SDIST_SHA256",
    "EXPECTED_WHEEL_SHA256",
    "INSTALLED_WHEEL_VERIFICATION_SCHEMA",
    "LearnedRuntimeReport",
    "LockedEnvironmentReport",
    "RUNTIME_FINGERPRINT_SCHEMA",
    "RUNTIME_PROVENANCE_SCHEMA",
    "RuntimeIntegrityError",
    "RuntimeIntegrityReport",
    "capture_learned_runtime_provenance",
    "derive_learned_runtime_fingerprint",
    "learned_runtime_manifest_fingerprint",
    "main",
    "make_learned_runtime_provenance",
    "not_applicable_learned_runtime_provenance",
    "parse_exact_lock",
    "validate_learned_runtime_provenance",
    "validate_installed_wheel_verification",
    "validate_locked_distributions",
    "verify_agentdojo_distribution",
    "verify_installed_distribution_against_wheel",
    "verify_runtime_environment",
]
